## AVOID CHANGES TO THIS FILE. IT IS USED TO RUN THE KAFKA AND ZOOKEPPER INSTANCES

version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    environment:
      - ZOOKEEPER_CLIENT_PORT=32181
    ports:
      - "32181:32181"

  kafka:
    image: confluentinc/cp-kafka:6.2.0
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    ports:
      - "9092:9092" 
    expose:
      - "9093" ## These ports are used in .py files for connecting to Kafka inside Docker
    restart: on-failure
    depends_on:
      - zookeeper

  jupyter:
    image: jupyter/minimal-notebook:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: jupyter
    volumes:
      - C:/path/to/spatial-streaming/:/home
    ports:
      - 8888:8888